DROP TABLE IF EXISTS customer_support.orders;

CREATE TABLE public.orders (
    order_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    product VARCHAR(100),
    status VARCHAR(50),
    order_date DATE,
    expected_delivery DATE,
    shipping_status VARCHAR(50),
    eligible_for_refund BOOLEAN DEFAULT TRUE,
    total DECIMAL(10,2),
    currency VARCHAR(10)
);

INSERT INTO public.orders
    (
        order_id,
        customer_name,
        product,
        status,
        order_date,
        expected_delivery,
        shipping_status,
        eligible_for_refund,
        total,
        currency
    )
VALUES
    (1001, 'Ahmed Ali', 'Laptop', 'Processing', '2026-09-20', '2026-09-30', 'Delayed', TRUE, 50000, 'EGP'),
    (1002, 'Omar Hassan', 'Headphones', 'Shipped', '2026-09-22', '2026-10-01', 'In Transit', TRUE, 3000, 'EGP'),
    (1003, 'Mohamed Salah', 'Keyboard', 'Cancelled', '2026-09-18', '2026-09-25', 'Cancelled', FALSE, 1500, 'EGP'),
    (1004, 'Youssef Mohamed', 'Mouse', 'Shipped', '2026-09-24', '2026-10-02', 'In Transit', TRUE, 800, 'EGP'),
    (1005, 'Ali Mahmoud', 'Monitor', 'Delivered', '2026-09-15', '2026-09-20', 'Delivered', TRUE, 10000, 'EGP')
ON CONFLICT (order_id) DO NOTHING;

CREATE TABLE tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    issue TEXT NOT NULL,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMPTZ DEFAULT NOW()
);